/* Generated By:JavaCC: Do not edit this line. Example2Constants.java */
/**
 * Simple brace matcher.
 */
package official.examples2;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Example2Constants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
