# 使用官方的 Java 11 基础镜像
FROM openjdk:11-jre-slim

# 设置工作目录在容器内
WORKDIR /opt



## 将你的 jar 文件复制到容器内
#COPY target/javamain-k8s-1.0-SNAPSHOT.jar /app/app.jar
## 暴露应用运行时的端口
## EXPOSE 8080
## 设置容器启动时执行的命令
#CMD ["java", "-jar", "app.jar"]

