<<<<<<< HEAD
#配置端口和path路径
server:
  port: 8074
spring:
  profiles:
    active: local
  jackson:
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 20
  servlet:
    multipart:
      enabled: true
      max-file-size: 450MB
      max-request-size: 500MB

logging:
=======
#配置端口和path路径
server:
  port: 8074
spring:
  profiles:
    active: local
  jackson:
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 20
  servlet:
    multipart:
      enabled: true
      max-file-size: 450MB
      max-request-size: 500MB

logging:
>>>>>>> 6d96e7e0c1420f234e11ca49b02863b7c5f79a7c
  config: classpath:logback-spring.xml