FROM ghcr.io/apache/flink-kubernetes-operator:91d67d9
RUN mkdir -p /opt/flink/plugins/flinkoperatorplugin
COPY target/javamain-flinkoperatorplugin-1.0-SNAPSHOT.jar /opt/flink/plugins/flinkoperatorplugin/javamain-flinkoperatorplugin-1.0-SNAPSHOT.jar
