/* Generated By:JavaCC: Do not edit this line. SimpleSqlParserConstants.java */
package extension.examples2;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OPERATOR = 9;
  /** RegularExpression Id. */
  int NAME = 10;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int QUO = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"AND\"",
    "<OPERATOR>",
    "<NAME>",
    "\".\"",
    "\",\"",
    "\"\"",
  };

}
